# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     name: compose
#     runs-on: [self-hosted]
#     steps:
#       - name: 🚚 Get latest code
#         uses: actions/checkout@v3
#       - name: 🔨 dependecies
#         run: |
#           npm install
#       - name: 🔨 Build Project
#         run: |
#           npm run build
#       - name: Docker Build image
#         run: |
#           echo "Build Started..."
#           docker build --pull --rm -f "Dockerfile" -t social-frontend:latest "."
#       - name: Docker Compose
#         run: |
#           echo "Compose Started..."
#           docker-compose up -d